#!/usr/bin/env bash
# This script installs Nginx, and sets up a default page containing 'Holberton School'

# Update package list
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Ensure Nginx is running
sudo systemctl start nginx
sudo systemctl enable nginx

# Replace default index.html with required content
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restart Nginx to apply changes
sudo systemctl restart nginx
